default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: controle-ponto_development

test:
  <<: *default
  database: controle-ponto_test

production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] %>
  username: <%= ENV['CONTROLE_PONTO_DATABASE_USER'] %>
  host: <%= ENV['CONTROLE_PONTO_DATABASE_HOST'] %>
  password: <%= ENV['CONTROLE_PONTO_DATABASE_PWD'] %>
